FROM openjdk:17
WORKDIR /springboot-cafebean/
COPY /Users/janmejaymohapatra/git/CafeBean-Backend/*.jar /springboot-cafebean/target/
EXPOSE 8080
CMD ["java","-jar","/springboot-cafebean/target/Cafe-Bean-0.0.1-SNAPSHOT.jar"]

